name: Build urlwatch

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: vimagick/dockerfiles/.github/actions/docker-build-notify@master
        with:
          context: '.'
          image_name: 'easypi/urlwatch'
          version_arg: 'URLWATCH_VERSION'
          version_value: '2.29'
